# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123
  jwt_secret: '1f257b6efdac2492a99361419c50981f46150c025bdcf03dfa3423f7a5d1251ee19318a5d870141dd51518a34fe17667a0a0cac4adaf32b133cdb519cfc25ae2'

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd8413138fa64c87c41d303b7404c933257dbd4392a2e405282b7ce4200a4936f8b0450d9a503dc089308d7518cc2871e0946dc5857ec6a604e0d6d1ff8bb79c

test:
  secret_key_base: cb465b2ec14333009c40366983a44a0bde75cc6e9da7ddaa4e35757caf8d8c3b97c499bec6af6c1fe6ca49d3edb2d22325cc5d532febb36b08803791d2165db1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
